"""empty message

Revision ID: 067d5c7f32d6
Revises: 85674cb38cf9
Create Date: 2016-11-29 22:32:21.155390

"""

# revision identifiers, used by Alembic.
revision = '067d5c7f32d6'
down_revision = '85674cb38cf9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exchange_membership',
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], )
    )
    op.drop_table('index_membership')
    op.drop_table('index')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('index_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'index_pkey'),
    sa.UniqueConstraint('name', name=u'index_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('index_membership',
    sa.Column('index_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], [u'company.id'], name=u'index_membership_company_id_fkey'),
    sa.ForeignKeyConstraint(['index_id'], [u'index.id'], name=u'index_membership_index_id_fkey')
    )
    op.drop_table('exchange_membership')
    op.drop_table('exchange')
    ### end Alembic commands ###
