"""empty message

Revision ID: 10b24b09b9df
Revises: 2dfec048b508
Create Date: 2017-09-27 17:16:35.806653

"""

# revision identifiers, used by Alembic.
revision = '10b24b09b9df'
down_revision = '2dfec048b508'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registration_code', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registration_code')
    # ### end Alembic commands ###
