"""empty message

Revision ID: 2dfec048b508
Revises: 4e405e15b903
Create Date: 2017-05-30 20:35:46.120631

"""

# revision identifiers, used by Alembic.
revision = '2dfec048b508'
down_revision = '4e405e15b903'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_password_change', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_password_change')
    ### end Alembic commands ###
