"""empty message

Revision ID: 3e20fa1bea82
Revises: 456a0816eca6
Create Date: 2016-11-18 21:51:26.914950

"""

# revision identifiers, used by Alembic.
revision = '3e20fa1bea82'
down_revision = '456a0816eca6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('sic_code', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'sic_code')
    ### end Alembic commands ###
