"""empty message

Revision ID: 456a0816eca6
Revises: bf500e65cf49
Create Date: 2016-11-08 22:22:39.442447

"""

# revision identifiers, used by Alembic.
revision = '456a0816eca6'
down_revision = 'bf500e65cf49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_membership',
    sa.Column('index_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['index.id'], )
    )
    op.drop_constraint(u'index_company_id_fkey', 'index', type_='foreignkey')
    op.drop_column(u'index', 'company_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'index', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'index_company_id_fkey', 'index', 'company', ['company_id'], ['id'])
    op.drop_table('index_membership')
    ### end Alembic commands ###
