"""empty message

Revision ID: 7dae452a20d9
Revises: e793a82a9887
Create Date: 2016-08-25 22:44:44.984764

"""

# revision identifiers, used by Alembic.
revision = '7dae452a20d9'
down_revision = 'e793a82a9887'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    ### end Alembic commands ###
