"""empty message

Revision ID: bf500e65cf49
Revises: abc32a2a229d
Create Date: 2016-11-07 23:08:02.331195

"""

# revision identifiers, used by Alembic.
revision = 'bf500e65cf49'
down_revision = 'abc32a2a229d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index')
    ### end Alembic commands ###
