"""empty message

Revision ID: d176b702636d
Revises: d5fc894c5936
Create Date: 2016-10-18 22:37:26.070033

"""

# revision identifiers, used by Alembic.
revision = 'd176b702636d'
down_revision = 'd5fc894c5936'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('one_per_company_per_day', 'indicators', ['date', 'company_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('one_per_company_per_day', 'indicators', type_='unique')
    ### end Alembic commands ###
