"""Add free cash flow fcf

Revision ID: d5fc894c5936
Revises: 7dae452a20d9
Create Date: 2016-08-25 22:48:58.023163

"""

# revision identifiers, used by Alembic.
revision = 'd5fc894c5936'
down_revision = '7dae452a20d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicators', sa.Column('fcf', sa.Float(), nullable=True, server_default="0.0"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators', 'fcf')
    ### end Alembic commands ###
