"""empty message

Revision ID: e793a82a9887
Revises: bfbea0c641bd
Create Date: 2016-07-26 22:57:24.361651

"""

# revision identifiers, used by Alembic.
revision = 'e793a82a9887'
down_revision = 'bfbea0c641bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, unique=True),
    sa.Column('symbol', sa.String(length=20), nullable=False, unique=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicators')
    op.drop_table('company')
    ### end Alembic commands ###
