"""empty message

Revision ID: fa8ea3cb6d2e
Revises: d176b702636d
Create Date: 2016-11-04 22:00:28.864582

"""

# revision identifiers, used by Alembic.
revision = 'fa8ea3cb6d2e'
down_revision = 'd176b702636d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'active')
    ### end Alembic commands ###
